<?php



?>

<!DOCTYPE HTML>
<HTml>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ALLIANCE AUTO-MOBILE</title>
     <!-- Css Styles -->
    <link rel="stylesheet" type="text/css" href="style.css" media="all">
    
</head>
 <body>
 <footer class="sub_header">
        <nav>
            <a href="Index.html"><img src="Img/logo.png" alt="logo not found"></a>
            <article class="nav-link" id="navLinks">
                <i class="fa fa-times" onclick="hideMenu()"></i>
                <ul>
                     <li> <a href="contact.php">CONTACT</a></li>
                     <li><a href="catolog.php">CATALOG</a></li>
                     <li><a href="payments.php">BUY</a></li>
                     <li> <a href="Blog.html" target="_blank">BLOG</a></li>
                     
                 </ul>
            </article>
            <i class="fa fa-bars" onclick="showMenu()"></i>
        </nav>

        <article class="text-box">
             <h1> WELCOME TO ALLIANCE <br> AUTOMOBILE</h1>
             <P>
            </P>
        </article>
    </footer>
</body>
</HTml>